ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false
    host: 0.0.0.0

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "aws"
  site-url: "https://riesfarms.github.io/aws"
  description: "Code for interacting with AWS services."
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: master
  repo-url: "https://github.com/riesfarms/aws"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/riesfarms/aws"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
