# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/aws',
                'doc_host': 'https://riesfarms.github.io',
                'git_url': 'https://github.com/riesfarms/aws',
                'lib_path': 'aws'},
  'syms': { 'aws.dynamodb': { 'aws.dynamodb.Config': ('dynamodb.html#config', 'aws/dynamodb.py'),
                              'aws.dynamodb.DynamoDB': ('dynamodb.html#dynamodb', 'aws/dynamodb.py'),
                              'aws.dynamodb.DynamoDB.__getattr__': ('dynamodb.html#__getattr__', 'aws/dynamodb.py'),
                              'aws.dynamodb.DynamoDB.__init__': ('dynamodb.html#__init__', 'aws/dynamodb.py'),
                              'aws.dynamodb.DynamoDB._init_resource': ('dynamodb.html#_init_resource', 'aws/dynamodb.py')}}}